<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SACCO Family Report - {{ $sacco ? $sacco->name : 'All SACCOs' }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Arial, sans-serif; font-size: 11px; color: #333; padding: 15px; background: #fff; }
        .report-header { text-align: center; margin-bottom: 15px; padding-bottom: 10px; border-bottom: 2px solid #333; }
        .report-header h1 { font-size: 20px; margin-bottom: 5px; color: #000; }
        .report-header h2 { font-size: 14px; margin-bottom: 8px; color: #666; }
        .report-meta { font-size: 10px; color: #666; }
        .section { margin-bottom: 15px; }
        .section-title { font-size: 13px; font-weight: bold; margin-bottom: 8px; padding: 5px 0; border-bottom: 1px solid #ddd; color: #000; }
        .info-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin-bottom: 15px; }
        .info-card { background: #f9f9f9; border: 1px solid #ddd; padding: 10px; }
        .info-card .label { font-size: 10px; color: #666; margin-bottom: 3px; }
        .info-card .value { font-size: 16px; font-weight: bold; color: #000; }
        .info-card .sub-value { font-size: 9px; color: #888; margin-top: 2px; }
        .demographics { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; margin-bottom: 15px; }
        .demo-card { background: #f9f9f9; border: 1px solid #ddd; padding: 8px; }
        .demo-card .demo-label { font-size: 10px; color: #666; margin-bottom: 5px; }
        .demo-item { display: flex; justify-content: space-between; margin: 3px 0; font-size: 10px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 10px; font-size: 10px; }
        th { background: #f5f5f5; padding: 6px; text-align: left; border: 1px solid #ddd; font-weight: bold; color: #000; }
        td { padding: 5px 6px; border: 1px solid #ddd; color: #333; }
        tr:nth-child(even) { background: #fafafa; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .medal { font-size: 14px; }
        .actions { margin-top: 15px; text-align: center; }
        .btn { display: inline-block; padding: 8px 20px; margin: 0 5px; background: #333; color: #fff; text-decoration: none; border: none; cursor: pointer; font-size: 11px; }
        .btn:hover { background: #555; }
        .trend-table { font-size: 10px; }
        .rate-good { color: #28a745; font-weight: bold; }
        .rate-medium { color: #ffc107; font-weight: bold; }
        .rate-poor { color: #dc3545; font-weight: bold; }
        @media print {
            .actions { display: none; }
            body { padding: 10px; }
        }
    </style>
</head>
<body>

    <!-- Report Header -->
    <div class="report-header">
        <h1>{{ $sacco ? $sacco->name : 'All SACCOs' }}</h1>
        <h2>Comprehensive Family Report</h2>
        <div class="report-meta">
            Generated on: {{ date('l, F j, Y \a\t g:i A') }}<br>
            Generated by: {{ Admin::user()->name }}
        </div>
    </div>

    <!-- Population Overview Section -->
    <div class="section">
        <div class="section-title">📊 Population Overview</div>
        
        <div class="info-grid">
            <div class="info-card">
                <div class="label">Total Members</div>
                <div class="value">{{ number_format($total_members) }}</div>
                <div class="sub-value">Active: {{ number_format($active_members) }}</div>
            </div>
            <div class="info-card">
                <div class="label">Status</div>
                <div class="value">{{ number_format($alive_members) }}</div>
                <div class="sub-value">Alive (Late: {{ number_format($deceased_members) }})</div>
            </div>
            <div class="info-card">
                <div class="label">Male Members</div>
                <div class="value">{{ number_format($male_members) }}</div>
                <div class="sub-value">{{ $total_members > 0 ? round(($male_members / $total_members) * 100, 1) : 0 }}%</div>
            </div>
            <div class="info-card">
                <div class="label">Female Members</div>
                <div class="value">{{ number_format($female_members) }}</div>
                <div class="sub-value">{{ $total_members > 0 ? round(($female_members / $total_members) * 100, 1) : 0 }}%</div>
            </div>
        </div>

        <div class="demographics">
            <div class="demo-card">
                <div class="demo-label">Age Distribution</div>
                @foreach($age_groups as $group => $count)
                <div class="demo-item">
                    <span>{{ $group }} years:</span>
                    <span><strong>{{ number_format($count) }}</strong> ({{ $total_members > 0 ? round(($count / $total_members) * 100, 1) : 0 }}%)</span>
                </div>
                @endforeach
            </div>
            <div class="demo-card">
                <div class="demo-label">Program Participation</div>
                <div class="demo-item">
                    <span>Total Programs:</span>
                    <span><strong>{{ number_format($total_programs) }}</strong></span>
                </div>
                <div class="demo-item">
                    <span>Active Programs:</span>
                    <span><strong>{{ number_format($active_programs) }}</strong></span>
                </div>
                <div class="demo-item">
                    <span>Total Records:</span>
                    <span><strong>{{ number_format($total_records) }}</strong></span>
                </div>
                <div class="demo-item">
                    <span>Payment Rate:</span>
                    <span><strong class="{{ $payment_rate >= 80 ? 'rate-good' : ($payment_rate >= 60 ? 'rate-medium' : 'rate-poor') }}">{{ $payment_rate }}%</strong></span>
                </div>
            </div>
            <div class="demo-card">
                <div class="demo-label">Collection Status</div>
                <div class="demo-item">
                    <span>Paid Records:</span>
                    <span><strong>{{ number_format($paid_records) }}</strong></span>
                </div>
                <div class="demo-item">
                    <span>Unpaid Records:</span>
                    <span><strong>{{ number_format($unpaid_records) }}</strong></span>
                </div>
                <div class="demo-item">
                    <span>Overdue Records:</span>
                    <span><strong>{{ number_format($overdue_count) }}</strong></span>
                </div>
                <div class="demo-item">
                    <span>Overdue Amount:</span>
                    <span><strong>UGX {{ number_format($overdue_amount) }}</strong></span>
                </div>
            </div>
        </div>
    </div>

    <!-- Financial Summary Section -->
    <div class="section">
        <div class="section-title">💰 Financial Summary</div>
        
        <div class="info-grid">
            <div class="info-card">
                <div class="label">Total Expected</div>
                <div class="value">UGX {{ number_format($total_expected) }}</div>
            </div>
            <div class="info-card">
                <div class="label">Total Collected</div>
                <div class="value">UGX {{ number_format($total_collected) }}</div>
                <div class="sub-value">Collection Rate: {{ $collection_rate }}%</div>
            </div>
            <div class="info-card">
                <div class="label">Outstanding Balance</div>
                <div class="value">UGX {{ number_format($total_balance) }}</div>
                <div class="sub-value">{{ $total_expected > 0 ? round(($total_balance / $total_expected) * 100, 1) : 0 }}% of Expected</div>
            </div>
            <div class="info-card">
                <div class="label">Avg Collection Rate</div>
                <div class="value" style="color: {{ $collection_rate >= 80 ? '#28a745' : ($collection_rate >= 60 ? '#ffc107' : '#dc3545') }}">{{ $collection_rate }}%</div>
                <div class="sub-value">Across {{ number_format($total_programs) }} Programs</div>
            </div>
        </div>
    </div>

    <!-- Top Contributors Section -->
    <div class="section">
        <div class="section-title">🏆 Top 10 Contributors</div>
        
        @if($top_contributors->count() > 0)
        <table>
            <thead>
                <tr>
                    <th style="width: 40px" class="text-center">Rank</th>
                    <th>Member Name</th>
                    <th>Member ID</th>
                    <th class="text-right">Total Paid (UGX)</th>
                    <th class="text-right">Records</th>
                </tr>
            </thead>
            <tbody>
                @foreach($top_contributors as $index => $contributor)
                <tr>
                    <td class="text-center">
                        @if($index == 0) <span class="medal">🥇</span>
                        @elseif($index == 1) <span class="medal">🥈</span>
                        @elseif($index == 2) <span class="medal">🥉</span>
                        @else {{ $index + 1 }}
                        @endif
                    </td>
                    <td>{{ $contributor->member->name }}</td>
                    <td>{{ $contributor->member->reg_number }}</td>
                    <td class="text-right"><strong>{{ number_format($contributor->total_paid) }}</strong></td>
                    <td class="text-right">
                        {{ number_format($contributor->record_count) }}
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @else
        <p style="text-align: center; color: #999; padding: 20px;">No payment records found</p>
        @endif
    </div>

    <!-- Recent Activity Section -->
    <div class="section">
        <div class="section-title">🕒 Recent Activity (Last 30 Days)</div>
        
        @if($recent_payments->count() > 0)
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Member</th>
                    <th>Program</th>
                    <th class="text-right">Amount (UGX)</th>
                    <th>Payment Method</th>
                </tr>
            </thead>
            <tbody>
                @foreach($recent_payments as $payment)
                <tr>
                    <td>{{ date('d/m/Y', strtotime($payment->payment_date)) }}</td>
                    <td>{{ $payment->member->name }}</td>
                    <td>{{ $payment->program->name }}</td>
                    <td class="text-right"><strong>{{ number_format($payment->paid_amount) }}</strong></td>
                    <td>{{ $payment->payment_method }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @else
        <p style="text-align: center; color: #999; padding: 20px;">No recent payments in the last 30 days</p>
        @endif
    </div>

    <!-- 12-Month Trend Section -->
    <div class="section">
        <div class="section-title">📈 12-Month Collection Trends</div>
        
        <table class="trend-table">
            <thead>
                <tr>
                    <th>Month</th>
                    <th class="text-right">Expected (UGX)</th>
                    <th class="text-right">Collected (UGX)</th>
                    <th class="text-right">Collection Rate</th>
                </tr>
            </thead>
            <tbody>
                @foreach($monthly_trends as $trend)
                <tr>
                    <td><strong>{{ $trend['month'] }}</strong></td>
                    <td class="text-right">{{ number_format($trend['expected']) }}</td>
                    <td class="text-right">{{ number_format($trend['paid']) }}</td>
                    <td class="text-right">
                        <span class="{{ $trend['rate'] >= 80 ? 'rate-good' : ($trend['rate'] >= 60 ? 'rate-medium' : 'rate-poor') }}">
                            {{ $trend['rate'] }}%
                        </span>
                    </td>
                </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr style="background: #f5f5f5; font-weight: bold;">
                    <td>TOTAL</td>
                    <td class="text-right">{{ number_format(array_sum(array_column($monthly_trends, 'expected'))) }}</td>
                    <td class="text-right">{{ number_format(array_sum(array_column($monthly_trends, 'paid'))) }}</td>
                    <td class="text-right">
                        @php
                            $total_exp = array_sum(array_column($monthly_trends, 'expected'));
                            $total_pd = array_sum(array_column($monthly_trends, 'paid'));
                            $avg_rate = $total_exp > 0 ? round(($total_pd / $total_exp) * 100, 1) : 0;
                        @endphp
                        <span class="{{ $avg_rate >= 80 ? 'rate-good' : ($avg_rate >= 60 ? 'rate-medium' : 'rate-poor') }}">
                            {{ $avg_rate }}%
                        </span>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>

    <!-- Actions -->
    <div class="actions">
        <button class="btn" onclick="window.print()">🖨️ Print Report</button>
        <button class="btn" onclick="copyReport()">📋 Copy Report</button>
        <a href="javascript:history.back()" class="btn">← Back</a>
    </div>

    <script>
        function copyReport() {
            const reportContent = document.body.innerText;
            navigator.clipboard.writeText(reportContent).then(() => {
                alert('Report content copied to clipboard!');
            }).catch(err => {
                console.error('Failed to copy: ', err);
            });
        }
    </script>

</body>
</html>
